// =============================================================================
// kernel/idt.cpp -- IDT setup & interrupt dispatch
// =============================================================================
#include "idt.h"
#include "io.h"
#include "libc/stdio.h"

namespace {

struct __attribute__((packed)) IdtEntry {
    uint16_t base_low;
    uint16_t selector;
    uint8_t  always0;
    uint8_t  flags;
    uint16_t base_high;
};

struct __attribute__((packed)) IdtPointer {
    uint16_t limit;
    uint32_t base;
};

constexpr int IDT_ENTRIES = 256;
IdtEntry idt_entries[IDT_ENTRIES];
IdtPointer idt_ptr;

InterruptHandler handlers[IDT_ENTRIES] = { nullptr };

void set_gate(uint8_t num, uint32_t base, uint16_t selector, uint8_t flags) {
    idt_entries[num].base_low  = base & 0xFFFF;
    idt_entries[num].base_high = (base >> 16) & 0xFFFF;
    idt_entries[num].selector  = selector;
    idt_entries[num].always0   = 0;
    idt_entries[num].flags     = flags;
}

// Remaps the 8259 Programmable Interrupt Controller so that hardware IRQs
// 0-15 fire interrupt vectors 32-47 instead of their BIOS defaults, which
// overlap with CPU exception vectors 0-15 and would otherwise be
// indistinguishable from them.
void remap_pic() {
    outb(0x20, 0x11); outb(0xA0, 0x11);  // start init sequence
    outb(0x21, 0x20); outb(0xA1, 0x28);  // master offset 32, slave offset 40
    outb(0x21, 0x04); outb(0xA1, 0x02);  // tell each PIC about the other
    outb(0x21, 0x01); outb(0xA1, 0x01);  // 8086 mode
    outb(0x21, 0x00); outb(0xA1, 0x00);  // unmask all IRQs
}

} // namespace

// Declare every isrN symbol generated by the assembly macros in isr_stubs.s.
extern "C" {
#define DECL_ISR(n) void isr##n();
DECL_ISR(0)  DECL_ISR(1)  DECL_ISR(2)  DECL_ISR(3)  DECL_ISR(4)  DECL_ISR(5)
DECL_ISR(6)  DECL_ISR(7)  DECL_ISR(8)  DECL_ISR(9)  DECL_ISR(10) DECL_ISR(11)
DECL_ISR(12) DECL_ISR(13) DECL_ISR(14) DECL_ISR(15) DECL_ISR(16) DECL_ISR(17)
DECL_ISR(18) DECL_ISR(19) DECL_ISR(20) DECL_ISR(21) DECL_ISR(22) DECL_ISR(23)
DECL_ISR(24) DECL_ISR(25) DECL_ISR(26) DECL_ISR(27) DECL_ISR(28) DECL_ISR(29)
DECL_ISR(30) DECL_ISR(31) DECL_ISR(32) DECL_ISR(33) DECL_ISR(34) DECL_ISR(35)
DECL_ISR(36) DECL_ISR(37) DECL_ISR(38) DECL_ISR(39) DECL_ISR(40) DECL_ISR(41)
DECL_ISR(42) DECL_ISR(43) DECL_ISR(44) DECL_ISR(45) DECL_ISR(46) DECL_ISR(47)
}

namespace idt {

void init() {
    idt_ptr.limit = sizeof(IdtEntry) * IDT_ENTRIES - 1;
    idt_ptr.base  = (uint32_t)&idt_entries;

    for (int i = 0; i < IDT_ENTRIES; i++) set_gate(i, 0, 0, 0);

    remap_pic();

    void (*stub_table[48])() = {
        isr0, isr1, isr2, isr3, isr4, isr5, isr6, isr7, isr8, isr9,
        isr10, isr11, isr12, isr13, isr14, isr15, isr16, isr17, isr18, isr19,
        isr20, isr21, isr22, isr23, isr24, isr25, isr26, isr27, isr28, isr29,
        isr30, isr31, isr32, isr33, isr34, isr35, isr36, isr37, isr38, isr39,
        isr40, isr41, isr42, isr43, isr44, isr45, isr46, isr47
    };

    for (int i = 0; i < 48; i++) {
        set_gate(i, (uint32_t)stub_table[i], 0x08 /* kernel code selector */, 0x8E);
    }

    asm volatile ("lidt (%0)" : : "r"(&idt_ptr));
    kprintf("[idt] loaded %d entries, PIC remapped to vectors 32-47\n", IDT_ENTRIES);
}

void register_handler(uint8_t num, InterruptHandler handler) {
    handlers[num] = handler;
}

} // namespace idt

// Called from isr_common_stub in isr_stubs.s for every exception and IRQ.
extern "C" void isr_common_handler(Registers* regs) {
    if (handlers[regs->int_no]) {
        handlers[regs->int_no](regs);
    } else if (regs->int_no < 32) {
        // Unhandled CPU exception -- this is fatal in our simple kernel.
        kprintf("\n[PANIC] Unhandled CPU exception %d, error code %d\n",
                regs->int_no, regs->err_code);
        for (;;) { asm volatile ("cli; hlt"); }
    }

    // Send End-Of-Interrupt to the PIC(s) for hardware IRQs (32-47).
    if (regs->int_no >= 32 && regs->int_no < 48) {
        if (regs->int_no >= 40) outb(0xA0, 0x20); // slave PIC
        outb(0x20, 0x20);                          // master PIC
    }
}
